export const languages = [
	{ code: "pt-BR", name: "Português (Brasil)", flag: "🇧🇷" },
	{ code: "pt-PT", name: "Português (Portugal)", flag: "🇵🇹" },
	{ code: "en-US", name: "English (United States)", flag: "🇺🇸" },
	{ code: "en-GB", name: "English (United Kingdom)", flag: "🇬🇧" },
	{ code: "en-AU", name: "English (Australia)", flag: "🇦🇺" },
	{ code: "en-CA", name: "English (Canada)", flag: "🇨🇦" },
	{ code: "es-ES", name: "Español (España)", flag: "🇪🇸" },
	{ code: "es-MX", name: "Español (México)", flag: "🇲🇽" },
	{ code: "es-AR", name: "Español (Argentina)", flag: "🇦🇷" },
	{ code: "es-CO", name: "Español (Colombia)", flag: "🇨🇴" },
	{ code: "fr-FR", name: "Français (France)", flag: "🇫🇷" },
	{ code: "fr-CA", name: "Français (Canada)", flag: "🇨🇦" },
	{ code: "de-DE", name: "Deutsch (Deutschland)", flag: "🇩🇪" },
	{ code: "de-AT", name: "Deutsch (Österreich)", flag: "🇦🇹" },
	{ code: "de-CH", name: "Deutsch (Schweiz)", flag: "🇨🇭" },
	{ code: "it-IT", name: "Italiano (Italia)", flag: "🇮🇹" },
	{ code: "ru-RU", name: "Русский (Россия)", flag: "🇷🇺" },
	{ code: "ja-JP", name: "日本語 (日本)", flag: "🇯🇵" },
	{ code: "ko-KR", name: "한국어 (대한민국)", flag: "🇰🇷" },
	{ code: "zh-CN", name: "中文 (中国)", flag: "🇨🇳" },
	{ code: "zh-TW", name: "中文 (台灣)", flag: "🇹🇼" },
	{ code: "zh-HK", name: "中文 (香港)", flag: "🇭🇰" },
	{ code: "ar-SA", name: "العربية (السعودية)", flag: "🇸🇦" },
	{ code: "ar-EG", name: "العربية (مصر)", flag: "🇪🇬" },
	{ code: "hi-IN", name: "हिन्दी (भारत)", flag: "🇮🇳" },
	{ code: "bn-IN", name: "বাংলা (ভারত)", flag: "🇮🇳" },
	{ code: "ta-IN", name: "தமிழ் (இந்தியா)", flag: "🇮🇳" },
	{ code: "te-IN", name: "తెలుగు (భారతదేశం)", flag: "🇮🇳" },
	{ code: "mr-IN", name: "मराठी (भारत)", flag: "🇮🇳" },
	{ code: "gu-IN", name: "ગુજરાતી (ભારત)", flag: "🇮🇳" },
	{ code: "kn-IN", name: "ಕನ್ನಡ (ಭಾರತ)", flag: "🇮🇳" },
	{ code: "ml-IN", name: "മലയാളം (ഇന്ത്യ)", flag: "🇮🇳" },
	{ code: "pa-IN", name: "ਪੰਜਾਬੀ (ਭਾਰਤ)", flag: "🇮🇳" },
	{ code: "ur-PK", name: "اردو (پاکستان)", flag: "🇵🇰" },
	{ code: "th-TH", name: "ไทย (ประเทศไทย)", flag: "🇹🇭" },
	{ code: "vi-VN", name: "Tiếng Việt (Việt Nam)", flag: "🇻🇳" },
	{ code: "id-ID", name: "Bahasa Indonesia (Indonesia)", flag: "🇮🇩" },
	{ code: "ms-MY", name: "Bahasa Melayu (Malaysia)", flag: "🇲🇾" },
	{ code: "tl-PH", name: "Filipino (Pilipinas)", flag: "🇵🇭" },
	{ code: "tr-TR", name: "Türkçe (Türkiye)", flag: "🇹🇷" },
	{ code: "pl-PL", name: "Polski (Polska)", flag: "🇵🇱" },
	{ code: "cs-CZ", name: "Čeština (Česká republika)", flag: "🇨🇿" },
	{ code: "sk-SK", name: "Slovenčina (Slovensko)", flag: "🇸🇰" },
	{ code: "hu-HU", name: "Magyar (Magyarország)", flag: "🇭🇺" },
	{ code: "ro-RO", name: "Română (România)", flag: "🇷🇴" },
	{ code: "bg-BG", name: "Български (България)", flag: "🇧🇬" },
	{ code: "hr-HR", name: "Hrvatski (Hrvatska)", flag: "🇭🇷" },
	{ code: "sr-RS", name: "Српски (Србија)", flag: "🇷🇸" },
	{ code: "sl-SI", name: "Slovenščina (Slovenija)", flag: "🇸🇮" },
	{ code: "et-EE", name: "Eesti (Eesti)", flag: "🇪🇪" },
	{ code: "lv-LV", name: "Latviešu (Latvija)", flag: "🇱🇻" },
	{ code: "lt-LT", name: "Lietuvių (Lietuva)", flag: "🇱🇹" },
	{ code: "fi-FI", name: "Suomi (Suomi)", flag: "🇫🇮" },
	{ code: "sv-SE", name: "Svenska (Sverige)", flag: "🇸🇪" },
	{ code: "da-DK", name: "Dansk (Danmark)", flag: "🇩🇰" },
	{ code: "no-NO", name: "Norsk (Norge)", flag: "🇳🇴" },
	{ code: "is-IS", name: "Íslenska (Ísland)", flag: "🇮🇸" },
	{ code: "nl-NL", name: "Nederlands (Nederland)", flag: "🇳🇱" },
	{ code: "nl-BE", name: "Nederlands (België)", flag: "🇧🇪" },
	{ code: "uk-UA", name: "Українська (Україна)", flag: "🇺🇦" },
	{ code: "be-BY", name: "Беларуская (Беларусь)", flag: "🇧🇾" },
	{ code: "el-GR", name: "Ελληνικά (Ελλάδα)", flag: "🇬🇷" },
	{ code: "he-IL", name: "עברית (ישראל)", flag: "🇮🇱" },
	{ code: "fa-IR", name: "فارسی (ایران)", flag: "🇮🇷" },
	{ code: "sw-KE", name: "Kiswahili (Kenya)", flag: "🇰🇪" },
	{ code: "am-ET", name: "አማርኛ (ኢትዮጵያ)", flag: "🇪🇹" },
	{ code: "zu-ZA", name: "isiZulu (iNingizimu Afrika)", flag: "🇿🇦" },
	{ code: "af-ZA", name: "Afrikaans (Suid-Afrika)", flag: "🇿🇦" }
];

export const getLanguageByCode = (code) => {
	return languages.find(lang => lang.code === code) || languages[0];
};

export const getLanguageOptions = () => {
	return languages.map(lang => ({
		value: lang.code,
		label: `${lang.flag} ${lang.name}`
	}));
};
